server:
  port: 8080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenzeweishare/miaosha-parent.git                 # 配置Git仓库的地址
          search-paths: miaosha-config-repo
          username:                                                                 # Git仓库的账号
          password:                                                                 # Git仓库的密码

