server:
  port: 8040
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


activemq:
  brokerURL: tcp://127.0.0.1:61616
  password: admin
  queueName: miaosha_queue
  pool:
    maxConnections: 10
  userName: admin
redis:
  password: 
  port: 6379
  ip: 127.0.0.1
  pool:
    maxIdle: 200
    testOnBorrow: true
    maxWait: 1000
    maxActive: 500

management:
  security:
    enabled: false
