server:
  port: 8002
spring:
  application:
    name: product-service
  redis:
    host: 127.0.0.1
    port: 6379
      max-idle: 8
      min-idele: 0
      max-active: 8
      max-wait: -1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true





management:
  security:
    enabled: false
