package com.miaosha.common.eum;

public enum SessionEnum {

	LOGIN_SESSION,
	USER_SESSION,
	USER_REGISTER_MESSAGE_CODE,
	USER_PASSWORD_MESSAGE_CODE,
	USER_LOGIN_MESSAGE_CODE,
	USER_BIND_MESSAGE_CODE,
	USER_BIND_BANK_MESSAGE_CODE,
	USER_EXTRACT_MESSAGE_CODE,
	USER_MODIFY_MOBILE_OLD_MESSAGE_CODE,
	USER_MODIFY_MOBILE_NEW_MESSAGE_CODE,
	
	MESSAGE_VALIDATE_CODE_SESSION,
	FIND_PASSWORD_USERNAME,
	
	SELLER_LOGIN_USERNAME,
	AGENCY_SELLER_LOGIN_USERNAME,
	MANAGER_LOGIN_SESSION,
	CURRENT_REQUEST_SESSION, 
	
	REPAIR_SHOP_MANAGER_SESSION,
	
	WEIXIN_WEB_ACCESS_TOKEN, 
	AGENCY_MANAGER_LOGIN_SESSION;
}
